package counselormgmtsystem.GUIprogram.AdminFrames;

import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Color;
import counselormgmtsystem.Admin;
import counselormgmtsystem.FileHandler;
import counselormgmtsystem.LoginFrame;
import counselormgmtsystem.adminGenerateReports;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author thesupreme
 */
 
    public class AdminFrame extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminFrame.class.getName());
        private Admin currentAdmin;

        /**
         * Creates new form AdminFrame
         */
        public AdminFrame(Admin admin) {
            this.currentAdmin = admin;
            initComponents();

            if (FileHandler.userList.isEmpty()) {
                new FileHandler().loadDataFromFiles();
            }

             
            try {
                
                ImageIcon originalUserIcon = new ImageIcon(getClass().getResource("/images/user (1).png"));
                usernameText.setText(admin.getUsername());
                adminPageUserIcon.setIcon(new ImageIcon(originalUserIcon.getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH)));
                userIcon.setIcon(new ImageIcon(originalUserIcon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH)));
                editBtn1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                saveBtn1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                logoutButton.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png")).getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
            } catch (Exception e) {
                logger.log(java.util.logging.Level.WARNING, "Image resource loading failed: " + e.getMessage());
            }

            // Populate fields with Admin details
            loadAdminData();

            // Lock fields initially
            setEditMode(false);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        sidebarPanel = new javax.swing.JPanel();
        profileHeader = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        navItem01 = new javax.swing.JPanel();
        navItemText01 = new javax.swing.JLabel();
        navItem02 = new javax.swing.JPanel();
        navItemText02 = new javax.swing.JLabel();
        navItem03 = new javax.swing.JPanel();
        navItemText03 = new javax.swing.JLabel();
        navItem04 = new javax.swing.JPanel();
        navItemText04 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        adminPageUserIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FNTF = new javax.swing.JTextField();
        UNTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmailTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ORTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CNTF = new javax.swing.JTextField();
        editBtn1 = new javax.swing.JButton();
        saveBtn1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        editBtn.setBackground(new java.awt.Color(0, 0, 0));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editBtn.setBorder(null);
        editBtn.setBorderPainted(false);
        editBtn.setContentAreaFilled(false);
        editBtn.addActionListener(this::editBtnActionPerformed);

        saveBtn.setBackground(new java.awt.Color(0, 0, 0));
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png"))); // NOI18N
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setFocusPainted(false);
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(0, 0, 102));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profileHeader.setBackground(new java.awt.Color(0, 0, 102));
        profileHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        userIcon.setText("jLabel1");
        profileHeader.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 37, 81, 88));

        usernameText.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        usernameText.setForeground(new java.awt.Color(255, 255, 255));
        usernameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileHeader.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 143, 160, 30));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setFocusPainted(false);
        logoutButton.addActionListener(this::logoutButtonActionPerformed);
        profileHeader.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 40, 40));

        sidebarPanel.add(profileHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 276, -1));

        navItem01.setBackground(new java.awt.Color(0, 0, 102));
        navItem01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navItem01MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem01MouseExited(evt);
            }
        });

        navItemText01.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText01.setForeground(new java.awt.Color(255, 255, 255));
        navItemText01.setText("Manage User Accounts");

        javax.swing.GroupLayout navItem01Layout = new javax.swing.GroupLayout(navItem01);
        navItem01.setLayout(navItem01Layout);
        navItem01Layout.setHorizontalGroup(
            navItem01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem01Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(navItemText01)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navItem01Layout.setVerticalGroup(
            navItem01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navItem01Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(navItemText01)
                .addGap(19, 19, 19))
        );

        sidebarPanel.add(navItem01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 213, 276, -1));

        navItem02.setBackground(new java.awt.Color(0, 0, 102));
        navItem02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navItem02MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem02MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem02MouseExited(evt);
            }
        });

        navItemText02.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText02.setForeground(new java.awt.Color(255, 255, 255));
        navItemText02.setText("Manage Staff Roster");

        javax.swing.GroupLayout navItem02Layout = new javax.swing.GroupLayout(navItem02);
        navItem02.setLayout(navItem02Layout);
        navItem02Layout.setHorizontalGroup(
            navItem02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem02Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(navItemText02)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navItem02Layout.setVerticalGroup(
            navItem02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navItem02Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(navItemText02)
                .addGap(20, 20, 20))
        );

        sidebarPanel.add(navItem02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 285, 276, -1));

        navItem03.setBackground(new java.awt.Color(0, 0, 102));
        navItem03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navItem03MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem03MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem03MouseExited(evt);
            }
        });

        navItemText03.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText03.setForeground(new java.awt.Color(255, 255, 255));
        navItemText03.setText("Appointment Statistics");

        javax.swing.GroupLayout navItem03Layout = new javax.swing.GroupLayout(navItem03);
        navItem03.setLayout(navItem03Layout);
        navItem03Layout.setHorizontalGroup(
            navItem03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem03Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(navItemText03)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navItem03Layout.setVerticalGroup(
            navItem03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem03Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(navItemText03)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        sidebarPanel.add(navItem03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 357, 276, -1));

        navItem04.setBackground(new java.awt.Color(0, 0, 102));
        navItem04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navItem04MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem04MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem04MouseExited(evt);
            }
        });

        navItemText04.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText04.setForeground(new java.awt.Color(255, 255, 255));
        navItemText04.setText("Generate Report");

        javax.swing.GroupLayout navItem04Layout = new javax.swing.GroupLayout(navItem04);
        navItem04.setLayout(navItem04Layout);
        navItem04Layout.setHorizontalGroup(
            navItem04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem04Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(navItemText04)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navItem04Layout.setVerticalGroup(
            navItem04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem04Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(navItemText04)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        sidebarPanel.add(navItem04, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 429, 276, -1));

        getContentPane().add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminPageUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        adminPageUserIcon.setText("jLabel1");
        jPanel1.add(adminPageUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 150, 160));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Personal Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Full Name: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, 30));

        FNTF.setBackground(new java.awt.Color(255, 255, 255));
        FNTF.setForeground(new java.awt.Color(0, 0, 0));
        FNTF.setText("John Doe");
        FNTF.addActionListener(this::FNTFActionPerformed);
        jPanel1.add(FNTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 230, 30));

        UNTF.setBackground(new java.awt.Color(255, 255, 255));
        UNTF.setForeground(new java.awt.Color(0, 0, 0));
        UNTF.setText("john_doe");
        UNTF.addActionListener(this::UNTFActionPerformed);
        jPanel1.add(UNTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 230, 30));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 80, 30));

        EmailTF.setBackground(new java.awt.Color(255, 255, 255));
        EmailTF.setForeground(new java.awt.Color(0, 0, 0));
        EmailTF.setText("john_doe@gmail.com");
        EmailTF.addActionListener(this::EmailTFActionPerformed);
        jPanel1.add(EmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 190, 30));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Save");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 40, 30));

        ORTF.setBackground(new java.awt.Color(255, 255, 255));
        ORTF.setForeground(new java.awt.Color(0, 0, 0));
        ORTF.setText("Level 3, Oklahoma");
        ORTF.addActionListener(this::ORTFActionPerformed);
        jPanel1.add(ORTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 190, 30));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Office Room:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 140, 30));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contact Number:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 30));

        CNTF.setBackground(new java.awt.Color(255, 255, 255));
        CNTF.setForeground(new java.awt.Color(0, 0, 0));
        CNTF.setText("0132312312");
        CNTF.addActionListener(this::CNTFActionPerformed);
        jPanel1.add(CNTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 190, 30));

        editBtn1.setBackground(new java.awt.Color(0, 0, 0));
        editBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editBtn1.setBorder(null);
        editBtn1.setBorderPainted(false);
        editBtn1.setContentAreaFilled(false);
        editBtn1.addActionListener(this::editBtn1ActionPerformed);
        jPanel1.add(editBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 40, 40));

        saveBtn1.setBackground(new java.awt.Color(0, 0, 0));
        saveBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png"))); // NOI18N
        saveBtn1.setBorder(null);
        saveBtn1.setBorderPainted(false);
        saveBtn1.setContentAreaFilled(false);
        saveBtn1.setFocusPainted(false);
        saveBtn1.addActionListener(this::saveBtn1ActionPerformed);
        jPanel1.add(saveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 40, 40));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 30));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Edit");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 660, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void loadAdminData() {
            if (currentAdmin != null) {
                usernameText.setText(currentAdmin.getUsername());
                FNTF.setText(currentAdmin.getfullName());
                UNTF.setText(currentAdmin.getUsername());
                EmailTF.setText(currentAdmin.getEmail());
                CNTF.setText(currentAdmin.getContactNumber());
                ORTF.setText(currentAdmin.getOfficeRoom());
            }
        }

        private void setEditMode(boolean enable) {
            FNTF.setEditable(enable);
            UNTF.setEditable(enable);
            EmailTF.setEditable(enable);
            CNTF.setEditable(enable);
            ORTF.setEditable(enable);

            saveBtn1.setEnabled(enable);
            editBtn1.setEnabled(!enable);
        }
    
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setLocationRelativeTo(null);
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void navItem01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem01MouseEntered
        // TODO add your handling code here:
        navItem01.setBackground(Color.orange);
        navItemText01.setForeground(Color.BLACK);

    }//GEN-LAST:event_navItem01MouseEntered

    private void navItem01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem01MouseExited
        // TODO add your handling code here:
        navItem01.setBackground(new Color(0, 0, 102));
        navItemText01.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem01MouseExited

    private void navItem02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem02MouseEntered
        // TODO add your handling code here:
        navItem02.setBackground(Color.orange);
        navItemText02.setForeground(Color.BLACK);
    }//GEN-LAST:event_navItem02MouseEntered

    private void navItem02MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem02MouseExited
        // TODO add your handling code here:
        navItem02.setBackground(new Color(0, 0, 102));
        navItemText02.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem02MouseExited

    private void navItem03MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem03MouseEntered
        navItem03.setBackground(Color.orange);
        navItemText03.setForeground(Color.BLACK);
    }//GEN-LAST:event_navItem03MouseEntered

    private void navItem03MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem03MouseExited
        navItem03.setBackground(new Color(0, 0, 102));
        navItemText03.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem03MouseExited

    private void navItem04MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem04MouseEntered
        navItem04.setBackground(Color.orange);
        navItemText04.setForeground(Color.BLACK);
    }//GEN-LAST:event_navItem04MouseEntered

    private void navItem04MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem04MouseExited
        navItem04.setBackground(new Color(0, 0, 102));
        navItemText04.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem04MouseExited

    private void CNTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNTFActionPerformed

    private void EmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTFActionPerformed

    private void UNTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UNTFActionPerformed

    private void FNTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNTFActionPerformed

    private void ORTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ORTFActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setEditMode(true);
        FNTF.requestFocus(); // Place cursor in the first box
    }//GEN-LAST:event_editBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
//        String newFullName = FNTF.getText().trim();
//        String newUsername = UNTF.getText().trim();
//        String newEmail = EmailTF.getText().trim();
//        String newContact = CNTF.getText().trim();
//
//        // Validation check
//        if (newFullName.isEmpty() || newUsername.isEmpty() || newEmail.isEmpty() || newContact.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        currentUser.setUsername(newUsername);
//        currentUser.setFullName(newFullName);
//        currentUser.setReceptionistEmail(newEmail);
//        currentUser.setReceptionistNumber(newContact);
//
//        usernameText.setText(currentUser.getUsername());
//        setEditMode(false);
//
//        JOptionPane.showMessageDialog(this, "Profile updated in session!");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn1ActionPerformed
        setEditMode(true);
        FNTF.requestFocus(); // Place cursor in the first box
    }//GEN-LAST:event_editBtn1ActionPerformed

    private void saveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtn1ActionPerformed
            String newFullName = FNTF.getText().trim();
            String newUsername = UNTF.getText().trim();
            String newEmail = EmailTF.getText().trim();
            String newContact = CNTF.getText().trim();
            String newOffice = ORTF.getText().trim();

            String validationError = FileHandler.validateData(newFullName, newContact, newEmail, null, false, currentAdmin.getID());
            if (validationError != null) {
                JOptionPane.showMessageDialog(this, validationError, "Input Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            currentAdmin.setFullName(newFullName);
            currentAdmin.setUsername(newUsername);
            currentAdmin.setEmail(newEmail);
            currentAdmin.setContactNumber(newContact);
            currentAdmin.setOfficeRoom(newOffice);

            // Update in central list and file
            currentAdmin.manageRecord(FileHandler.userList, currentAdmin, "UPDATE");
            new FileHandler().saveDataToFiles();

            usernameText.setText(currentAdmin.getUsername());
            setEditMode(false);

            JOptionPane.showMessageDialog(this, "Profile successfully updated!");
    }//GEN-LAST:event_saveBtn1ActionPerformed

    private void navItem01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem01MouseClicked
        manageUsersAdmin userPage = new manageUsersAdmin(this.currentAdmin);
        userPage.setLocationRelativeTo(null);
        userPage.setVisible(true);
    }//GEN-LAST:event_navItem01MouseClicked

    private void navItem02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem02MouseClicked
        adminManageRoster rosterPage = new adminManageRoster(this.currentAdmin);
        rosterPage.setLocationRelativeTo(null);
        rosterPage.setVisible(true);
    }//GEN-LAST:event_navItem02MouseClicked

    private void navItem03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem03MouseClicked
        adminApptStats apptStatsPage = new adminApptStats(this.currentAdmin);
        apptStatsPage.setLocationRelativeTo(null);
        apptStatsPage.setVisible(true);
    }//GEN-LAST:event_navItem03MouseClicked

    private void navItem04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem04MouseClicked
        adminGenerateReports reportPage = new adminGenerateReports(this.currentAdmin);
        reportPage.setLocationRelativeTo(null);
        reportPage.setVisible(true);
    }//GEN-LAST:event_navItem04MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNTF;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JTextField FNTF;
    private javax.swing.JTextField ORTF;
    private javax.swing.JTextField UNTF;
    private javax.swing.JLabel adminPageUserIcon;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel navItem01;
    private javax.swing.JPanel navItem02;
    private javax.swing.JPanel navItem03;
    private javax.swing.JPanel navItem04;
    private javax.swing.JLabel navItemText01;
    private javax.swing.JLabel navItemText02;
    private javax.swing.JLabel navItemText03;
    private javax.swing.JLabel navItemText04;
    private javax.swing.JPanel profileHeader;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton saveBtn1;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
