/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package counselormgmtsystem.GUIprogram.AdminFrames;

import counselormgmtsystem.*;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author thesupreme
 */
public class manageUsersAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(manageUsersAdmin.class.getName());
    private Admin currentAdmin;

    /**
     * Creates new form manageUsersAdmin
     */
    public manageUsersAdmin(Admin admin) {
        initComponents();
        this.currentAdmin = admin;
        
        try {
            java.net.URL recepUrl = getClass().getResource("/images/recep.png");
            if (recepUrl != null) {
                recepUserIconAvatar1.setIcon(new ImageIcon(new ImageIcon(recepUrl).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
            }

            java.net.URL advUrl = getClass().getResource("/images/advisory.png");
            if (advUrl != null) {
                counselorUserIconAvatar1.setIcon(new ImageIcon(new ImageIcon(advUrl).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
            }
        } catch (Exception e) {
            System.out.println("Image failed to load on manage users screen: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        recepUserIconAvatar = new javax.swing.JLabel();
        recepUserBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        counselorUserIconAvatar = new javax.swing.JLabel();
        counselorUserBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        recepUserIconAvatar1 = new javax.swing.JLabel();
        recepUserBtn1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        counselorUserIconAvatar1 = new javax.swing.JLabel();
        counselorUserBtn1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Select a user account type:");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(recepUserIconAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 42, 116, 109));

        recepUserBtn.setText("Receptionist");
        recepUserBtn.addActionListener(this::recepUserBtnActionPerformed);
        jPanel2.add(recepUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 184, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(counselorUserIconAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 43, 123, 109));

        counselorUserBtn.setText("Counselor");
        counselorUserBtn.addActionListener(this::counselorUserBtnActionPerformed);
        jPanel3.add(counselorUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 185, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Select a user account type:");

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(recepUserIconAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 42, 116, 109));

        recepUserBtn1.setText("Receptionist");
        recepUserBtn1.addActionListener(this::recepUserBtn1ActionPerformed);
        jPanel6.add(recepUserBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 184, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(counselorUserIconAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 43, 123, 109));

        counselorUserBtn1.setText("Counselor");
        counselorUserBtn1.addActionListener(this::counselorUserBtn1ActionPerformed);
        jPanel7.add(counselorUserBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 185, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manage Users");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recepUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepUserBtnActionPerformed
        adminManageRecep recepPage = new adminManageRecep(this.currentAdmin);
        recepPage.setLocationRelativeTo(null);
        recepPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_recepUserBtnActionPerformed

    private void counselorUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counselorUserBtnActionPerformed
        adminManageCounselor counsPage = new adminManageCounselor(this.currentAdmin);
        counsPage.setLocationRelativeTo(null);
        counsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_counselorUserBtnActionPerformed

    private void recepUserBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepUserBtn1ActionPerformed
        adminManageRecep recepPage = new adminManageRecep(this.currentAdmin);
        recepPage.setLocationRelativeTo(null);
        recepPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_recepUserBtn1ActionPerformed

    private void counselorUserBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counselorUserBtn1ActionPerformed
        adminManageCounselor counsPage = new adminManageCounselor(this.currentAdmin);
        counsPage.setLocationRelativeTo(null);
        counsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_counselorUserBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton counselorUserBtn;
    private javax.swing.JButton counselorUserBtn1;
    private javax.swing.JLabel counselorUserIconAvatar;
    private javax.swing.JLabel counselorUserIconAvatar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton recepUserBtn;
    private javax.swing.JButton recepUserBtn1;
    private javax.swing.JLabel recepUserIconAvatar;
    private javax.swing.JLabel recepUserIconAvatar1;
    // End of variables declaration//GEN-END:variables
}
