package counselormgmtsystem;

import counselormgmtsystem.GUIprogram.AdminFrames.AdminFrame;
import counselormgmtsystem.GUIprogram.CounselorFrames.CounselorMainFrame;
import counselormgmtsystem.GUIprogram.ReceptionistFrames.ReceptionistMainFrame;
import counselormgmtsystem.GUIprogram.StudentFrames.StudentMainFrame;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author thesupreme
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    private int loginAttempts = 0;
    private static final int MAX_ATTEMPTS = 3;
    private Timer lockoutTimer;
    private int lockoutSecondsRemaining = 30;

    /**
     * Creates new form NewJFrame
     */
    public LoginFrame() {
        initComponents();

        passwordTF.setText("");

        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/images/login_icon.png"));
        Image rawImage = originalIcon.getImage();
        Image resizedImage = rawImage.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        loginIcon.setIcon(new ImageIcon(resizedImage));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginIcon = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        loginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_icon.png"))); // NOI18N
        loginIcon.setBorder(null);
        loginIcon.setBorderPainted(false);
        loginIcon.setContentAreaFilled(false);
        loginIcon.addActionListener(this::loginIconActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(loginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(loginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To Counselor Management System!");

        usernameTF.setForeground(new java.awt.Color(102, 102, 102));
        usernameTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameTF.addActionListener(this::usernameTFActionPerformed);

        passwordTF.setForeground(new java.awt.Color(102, 102, 102));
        passwordTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Password:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Username: ");

        loginBtn.setBackground(new java.awt.Color(0, 0, 102));
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(this::loginBtnActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(loginBtn)))
                .addGap(148, 148, 148))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(loginBtn)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIconActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_loginIconActionPerformed

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTFActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username = usernameTF.getText().trim();
        String passwordText = new String(passwordTF.getPassword()).trim();

        // 1. MANDATORY INPUT CHECK
        if (username.isEmpty() || passwordText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both Username and Password.", "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        User authenticatedUser = null;

        // 2. USER AUTHENTICATION & STATUS CHECK
        for (User user : FileHandler.userList) {
            if (username.equals(user.username) && passwordText.equals(user.password)) {
                authenticatedUser = user;
                break;
            }
        }

        if (authenticatedUser != null) {
            // Check Account Status
            String status = (authenticatedUser.status != null) ? authenticatedUser.status : "Active";
            if (status.equalsIgnoreCase("Inactive")) {
                JOptionPane.showMessageDialog(this, "Your account is currently inactive. Please contact the administrator.", "Account Disabled", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // SUCCESSFUL LOGIN: Reset attempt counter and redirect
            loginAttempts = 0;
            this.dispose();

            if (authenticatedUser instanceof Admin admin) {
                AdminFrame adminFrame = new AdminFrame(admin);
                adminFrame.setLocationRelativeTo(null);
                adminFrame.setVisible(true);
            } else if (authenticatedUser instanceof Receptionist recep) {
                ReceptionistMainFrame recepFrame = new ReceptionistMainFrame(recep);
                recepFrame.setLocationRelativeTo(null);
                recepFrame.setVisible(true);
            } else if (authenticatedUser instanceof Counselor counselor) {
                CounselorMainFrame counselorFrame = new CounselorMainFrame(counselor);
                counselorFrame.setLocationRelativeTo(null);
                counselorFrame.setVisible(true);
            } else if (authenticatedUser instanceof Student student) {
                StudentMainFrame studentFrame = new StudentMainFrame(student);
                studentFrame.setLocationRelativeTo(null);
                studentFrame.setVisible(true);
            }
        } else {
            // 3. FAILED LOGIN ATTEMPT HANDLING
            loginAttempts++;
            int remaining = MAX_ATTEMPTS - loginAttempts;

            if (loginAttempts >= MAX_ATTEMPTS) {
                triggerLockout();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Username or Password.\nAttempts remaining: " + remaining, "Login Failed", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void triggerLockout() {
        loginBtn.setEnabled(false);
        usernameTF.setEnabled(false);
        passwordTF.setEnabled(false);
        lockoutSecondsRemaining = 30;

        JOptionPane.showMessageDialog(this, "Too many failed attempts! Login system locked for 30 seconds.", "Account Locked", JOptionPane.ERROR_MESSAGE);

        lockoutTimer = new Timer(1000, e -> {
            lockoutSecondsRemaining--;
            loginBtn.setText("Locked (" + lockoutSecondsRemaining + "s)");

            if (lockoutSecondsRemaining <= 0) {
                lockoutTimer.stop();
                loginAttempts = 0;
                loginBtn.setText("Login");
                loginBtn.setEnabled(true);
                usernameTF.setEnabled(true);
                passwordTF.setEnabled(true);
            }
        });
        lockoutTimer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        // read the files and initialize
        FileHandler fh = new FileHandler();
        fh.loadDataFromFiles();

        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton loginIcon;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
