/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package counselormgmtsystem.GUIprogram.CounselorFrames;

import counselormgmtsystem.Appointment;
import counselormgmtsystem.ConsultationRecords;
import counselormgmtsystem.Counselor;
import counselormgmtsystem.FileHandler;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author tzhen
 */
public class StudentConsultationRecordsFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentConsultationRecordsFrame.class.getName());
    private Counselor currentCounselor;

    /**
     * Creates new form StudentConsultationRecordsFrame
     */
    public StudentConsultationRecordsFrame(Counselor counselor) {
        this.currentCounselor = counselor;
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        FileHandler fileHandler = new FileHandler();

        if (FileHandler.userList.isEmpty() && FileHandler.consultList.isEmpty()) {
            fileHandler.loadDataFromFiles();
        }

        populateDateComboBox();
        populateTable();

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                populateFormFromSelection();
            }
        });

        setSize(850, 540);

    }

    private void populateDateComboBox() {
        if (dateComboBox == null) {
            return;
        }
        dateComboBox.removeAllItems();

        List<String> uniqueDates = new ArrayList<>();

        if (currentCounselor != null && FileHandler.apptList != null) {
            for (Appointment appt : FileHandler.apptList) {
                if (appt.getCounselorID() != null
                        && appt.getCounselorID().equalsIgnoreCase(currentCounselor.getID())
                        && !appt.getStatus().equalsIgnoreCase("Cancelled")) {

                    if (!uniqueDates.contains(appt.getDate())) {
                        uniqueDates.add(appt.getDate());
                        dateComboBox.addItem(appt.getDate());
                    }
                }
            }
        }

        if (dateComboBox.getItemCount() > 0) {
            dateComboBox.setSelectedIndex(0);
            updateApptIDComboBox(); // Auto-populate appointment IDs for the first date
        }
    }

    private void updateApptIDComboBox() {
        if (apptIDComboBox == null || dateComboBox == null || dateComboBox.getSelectedItem() == null) {
            if (apptIDComboBox != null) {
                apptIDComboBox.removeAllItems();
            }
            return;
        }

        String selectedDate = (String) dateComboBox.getSelectedItem();
        apptIDComboBox.removeAllItems();

        if (currentCounselor != null && FileHandler.apptList != null) {
            for (Appointment appt : FileHandler.apptList) {
                if (appt.getCounselorID() != null
                        && appt.getCounselorID().equalsIgnoreCase(currentCounselor.getID())
                        && appt.getDate().equals(selectedDate)
                        && !appt.getStatus().equalsIgnoreCase("Cancelled")) {

                    apptIDComboBox.addItem(appt.getApptID());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        notesArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        recommendationsArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        apptIDComboBox = new javax.swing.JComboBox<>();
        dateComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Record Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Appointment ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel6.setText("Date");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        jLabel7.setText("Notes");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, -1));

        jLabel8.setText("Recommendations");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        notesArea.setColumns(20);
        notesArea.setRows(5);
        jScrollPane4.setViewportView(notesArea);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 260, 120));

        recommendationsArea.setColumns(20);
        recommendationsArea.setRows(5);
        jScrollPane5.setViewportView(recommendationsArea);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 260, 140));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 850, 40));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 850, 30));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 850, 30));

        apptIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(apptIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 140, -1));

        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateComboBox.addActionListener(this::dateComboBoxActionPerformed);
        jPanel2.add(dateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 430, 420));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Existing Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Record ID", "Student ID", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 368, 385));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 390, 420));

        addButton.setBackground(new java.awt.Color(255, 255, 51));
        addButton.setForeground(new java.awt.Color(0, 0, 0));
        addButton.setText("Add  Record");
        addButton.addActionListener(this::addButtonActionPerformed);
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 180, -1));

        updateButton.setBackground(new java.awt.Color(0, 0, 128));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update Record");
        updateButton.addActionListener(this::updateButtonActionPerformed);
        jPanel1.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 120, -1));

        deleteButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete Record");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-note-50.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 50, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 128));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Consultation Records");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 840, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        addRecordToTable();

    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        updateSelectedRecord();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        deleteSelectedRecord();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void dateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboBoxActionPerformed
        updateApptIDComboBox();
    }//GEN-LAST:event_dateComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    private void populateTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (ConsultationRecords record : FileHandler.consultList) {
            // Show records logged by this counselor
            if (currentCounselor != null && record.getCounselorID().equalsIgnoreCase(currentCounselor.getID())) {
                model.addRow(new Object[]{record.getRecordID(), record.getStudentID(), record.getDate()});
            }
        }
    }

    private void populateFormFromSelection() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String recordID = (String) jTable1.getValueAt(selectedRow, 0);

            for (ConsultationRecords record : FileHandler.consultList) {
                if (record.getRecordID().equals(recordID)) {
                    // Match and select Date
                    if (dateComboBox != null) {
                        dateComboBox.setSelectedItem(record.getDate());
                    }
                    // Match and select Appt ID
                    if (apptIDComboBox != null) {
                        apptIDComboBox.setSelectedItem(record.getAppointmentID());
                    }
                    notesArea.setText(record.getNotes());
                    recommendationsArea.setText(record.getRecommendations());
                    break;
                }
            }
        }
    }

    // --- HELPER TO FIND STUDENT ID FROM APPOINTMENT ID ---
    private String findStudentIDFromAppt(String apptID) {
        for (Appointment a : FileHandler.apptList) {
            if (a.getApptID().equalsIgnoreCase(apptID)) {
                return a.getStudentID();
            }
        }
        return "STD000"; // Fallback default
    }

    private void addRecordToTable() {
        if (dateComboBox.getSelectedItem() == null || apptIDComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a valid Date and Appointment ID.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String apptID = (String) apptIDComboBox.getSelectedItem();
        String dateStr = (String) dateComboBox.getSelectedItem();
        String notes = notesArea.getText().trim();
        String recs = recommendationsArea.getText().trim();

        if (notes.isEmpty() || recs.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Notes and Recommendations cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Auto-generate Record ID
        String newRecordID = FileHandler.generateUserID("REC", FileHandler.consultList, ConsultationRecords::getRecordID);
        String studentID = findStudentIDFromAppt(apptID);
        String counselorID = (currentCounselor != null) ? currentCounselor.getID() : "CNS001";

        ConsultationRecords record = new ConsultationRecords(
                newRecordID, apptID, studentID, counselorID, dateStr, notes, recs
        );

        FileHandler.consultList.add(record);
        FileHandler.saveDataToFiles();

        populateTable();
        clearFields();
        JOptionPane.showMessageDialog(this, "Consultation Record " + newRecordID + " added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    private void updateSelectedRecord() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a record from the table to update.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (dateComboBox.getSelectedItem() == null || apptIDComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a valid Date and Appointment ID.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String recordID = (String) jTable1.getValueAt(selectedRow, 0);
        String apptID = (String) apptIDComboBox.getSelectedItem();
        String dateStr = (String) dateComboBox.getSelectedItem();
        String notes = notesArea.getText().trim();
        String recs = recommendationsArea.getText().trim();

        if (notes.isEmpty() || recs.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Notes and Recommendations cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (ConsultationRecords record : FileHandler.consultList) {
            if (record.getRecordID().equals(recordID)) {
                record.setAppointmentID(apptID);
                record.setStudentID(findStudentIDFromAppt(apptID));
                record.setDate(dateStr);
                record.setNotes(notes);
                record.setRecommendations(recs);
                break;
            }
        }

        FileHandler.saveDataToFiles();
        populateTable();
        clearFields();
        JOptionPane.showMessageDialog(this, "Record updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    private void deleteSelectedRecord() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a record to delete.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this consultation record?",
                "Confirm Deletion", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            FileHandler.consultList.remove(selectedRow);
            FileHandler.saveDataToFiles();

            populateTable();
            clearFields();
            JOptionPane.showMessageDialog(this, "Record deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void clearFields() {
        if (dateComboBox.getItemCount() > 0) {
            dateComboBox.setSelectedIndex(0);
        }
        notesArea.setText("");
        recommendationsArea.setText("");
        jTable1.clearSelection();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> apptIDComboBox;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea notesArea;
    private javax.swing.JTextArea recommendationsArea;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
