/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package counselormgmtsystem.GUIprogram.CounselorFrames;

import counselormgmtsystem.ConsultationRecords;
import counselormgmtsystem.Counselor;
import counselormgmtsystem.FileHandler;

/**
 *
 * @author tzhen
 */
public class StudentConsultationRecordsFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentConsultationRecordsFrame.class.getName());
    private Counselor currentCounselor;
    /**
     * Creates new form StudentConsultationRecordsFrame
     */
   public StudentConsultationRecordsFrame(Counselor counselor) {
        this.currentCounselor = counselor;
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        FileHandler fileHandler = new FileHandler();
        
        
        if (FileHandler.userList.isEmpty() && FileHandler.consultList.isEmpty()) {
            fileHandler.loadDataFromFiles();
        }
        
        
        populateTable();
        
        
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                populateFormFromSelection();
            }
        });
        
        
        setSize(850, 540);
        
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        recordIDField = new javax.swing.JTextField();
        appointmentIDField = new javax.swing.JTextField();
        studentIDField = new javax.swing.JTextField();
        counselorIDField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        notesArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        recommendationsArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Record Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Record ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 21, 62, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Appointment ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 49, -1, -1));

        jLabel4.setText("Student ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 77, 100, -1));

        jLabel5.setText("Counselor ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 102, 100, -1));

        jLabel6.setText("Date");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 136, 100, -1));

        jLabel7.setText("Notes");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, -1));

        jLabel8.setText("Recommendations");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        jPanel2.add(recordIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 80, -1));

        appointmentIDField.addActionListener(this::appointmentIDFieldActionPerformed);
        jPanel2.add(appointmentIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 80, -1));

        studentIDField.addActionListener(this::studentIDFieldActionPerformed);
        jPanel2.add(studentIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 80, -1));

        counselorIDField.setText("CNS001");
        counselorIDField.addActionListener(this::counselorIDFieldActionPerformed);
        jPanel2.add(counselorIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 110, 80, -1));

        dateField.addActionListener(this::dateFieldActionPerformed);
        jPanel2.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 80, -1));

        notesArea.setColumns(20);
        notesArea.setRows(5);
        jScrollPane4.setViewportView(notesArea);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 176, 260, 100));

        recommendationsArea.setColumns(20);
        recommendationsArea.setRows(5);
        jScrollPane5.setViewportView(recommendationsArea);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 286, 260, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 850, 40));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 850, 30));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 850, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 430, 410));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Existing Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Record ID", "Student ID", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 368, 385));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 390, 420));

        addButton.setBackground(new java.awt.Color(255, 255, 51));
        addButton.setForeground(new java.awt.Color(0, 0, 0));
        addButton.setText("Add  Record");
        addButton.addActionListener(this::addButtonActionPerformed);
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 180, -1));

        updateButton.setBackground(new java.awt.Color(0, 0, 128));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update Record");
        updateButton.addActionListener(this::updateButtonActionPerformed);
        jPanel1.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 120, -1));

        deleteButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete Record");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-note-50.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 50, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 128));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Consultation Records");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 840, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void counselorIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counselorIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_counselorIDFieldActionPerformed

    private void studentIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        addRecordToTable();
     
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
       updateSelectedRecord();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        deleteSelectedRecord();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void appointmentIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentIDFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void populateTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 

        for (ConsultationRecords record : FileHandler.consultList) {
            model.addRow(new Object[]{record.getRecordID(), record.getStudentID(), record.getDate()});
        }
    }

    private void populateFormFromSelection() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            ConsultationRecords record = FileHandler.consultList.get(selectedRow);
            recordIDField.setText(record.getRecordID());
            appointmentIDField.setText(record.getAppointmentID());
            studentIDField.setText(record.getStudentID());
            counselorIDField.setText(record.getCounselorID());
            dateField.setText(record.getDate());
            notesArea.setText(record.getNotes());
            recommendationsArea.setText(record.getRecommendations());
        }
    }

    private void addRecordToTable() {
        if (recordIDField.getText().trim().isEmpty() || appointmentIDField.getText().trim().isEmpty()
                || studentIDField.getText().trim().isEmpty() || counselorIDField.getText().trim().isEmpty()
                || dateField.getText().trim().isEmpty() || notesArea.getText().trim().isEmpty()
                || recommendationsArea.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        ConsultationRecords record = new ConsultationRecords(
                recordIDField.getText().trim(), appointmentIDField.getText().trim(),
                studentIDField.getText().trim(), counselorIDField.getText().trim(),
                dateField.getText().trim(), notesArea.getText().trim(), recommendationsArea.getText().trim());

        FileHandler fileHandler = new FileHandler();
        record.addToConsultationList(FileHandler.consultList);
        fileHandler.saveDataToFiles();
        
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{record.getRecordID(), record.getStudentID(), record.getDate()});
        
        clearFields();
        javax.swing.JOptionPane.showMessageDialog(this, "Record added successfully.");
    }

    private void updateSelectedRecord() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a record from the table to update.");
            return;
        }

        if (recordIDField.getText().trim().isEmpty() || appointmentIDField.getText().trim().isEmpty()
                || studentIDField.getText().trim().isEmpty() || counselorIDField.getText().trim().isEmpty()
                || dateField.getText().trim().isEmpty() || notesArea.getText().trim().isEmpty()
                || recommendationsArea.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields before updating.");
            return;
        }

        ConsultationRecords record = FileHandler.consultList.get(selectedRow);
        record.setRecordID(recordIDField.getText().trim());
        record.setAppointmentID(appointmentIDField.getText().trim());
        record.setStudentID(studentIDField.getText().trim());
        record.setCounselorID(counselorIDField.getText().trim());
        record.setDate(dateField.getText().trim());
        record.setNotes(notesArea.getText().trim());
        record.setRecommendations(recommendationsArea.getText().trim());

        FileHandler fileHandler = new FileHandler();
        fileHandler.saveDataToFiles();

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setValueAt(record.getRecordID(), selectedRow, 0);
        model.setValueAt(record.getStudentID(), selectedRow, 1);
        model.setValueAt(record.getDate(), selectedRow, 2);

        clearFields();
        javax.swing.JOptionPane.showMessageDialog(this, "Record updated successfully.");
    }

    private void deleteSelectedRecord() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a record to delete.");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete this consultation record?", 
                "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            FileHandler.consultList.remove(selectedRow);
            
            FileHandler fileHandler = new FileHandler();
            fileHandler.saveDataToFiles();
            
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRow);
            
            clearFields();
            javax.swing.JOptionPane.showMessageDialog(this, "Record deleted successfully.");
        }
    }

    private void clearFields() {
        recordIDField.setText("");
        appointmentIDField.setText("");
        studentIDField.setText("");
        dateField.setText("");
        notesArea.setText("");
        recommendationsArea.setText("");
        jTable1.clearSelection();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField appointmentIDField;
    private javax.swing.JTextField counselorIDField;
    private javax.swing.JTextField dateField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea notesArea;
    private javax.swing.JTextArea recommendationsArea;
    private javax.swing.JTextField recordIDField;
    private javax.swing.JTextField studentIDField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
