/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package counselormgmtsystem.GUIprogram.ReceptionistFrames;

import counselormgmtsystem.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author thesupreme
 */public class ReceptionistMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReceptionistMainFrame.class.getName());
    private Receptionist currentUser;
    public ReceptionistMainFrame(Receptionist receptionist) {
        this.currentUser = receptionist;
        initComponents();
        ImageIcon originalUserIcon = new ImageIcon(getClass().getResource("/images/user (1).png"));
        usernameText.setText(currentUser.getUsername());
        Image rawUserImage = originalUserIcon.getImage();
        Image resizedUserImage = rawUserImage.getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        
        FNTF.setText(currentUser.getfullName());
        UNTF.setText(currentUser.getUsername());
        EmailTF.setText(currentUser.getReceptionistEmail());
        CNTF.setText(currentUser.getReceptionistNumber());
        
        //keep TF non-editable
        setEditMode(false);        
      
        editBtn.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));        
        saveBtn.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));        
        userIcon.setIcon(new ImageIcon(resizedUserImage));
        logoutButton.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png")).getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));        
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.out.println("App closing... saving all data to files.");
                FileHandler fh = new FileHandler();
                fh.saveDataToFiles();
            }
        });
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jLabel1 = new javax.swing.JLabel();
        adminPageUserIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        contentPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        adminPageUserIcon1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EmailTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CNTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        FNTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        UNTF = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        sidebarPanel = new javax.swing.JPanel();
        profileHeader = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        navItem01 = new javax.swing.JPanel();
        navItemText01 = new javax.swing.JLabel();
        navItem02 = new javax.swing.JPanel();
        navItemText02 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Personal Information");

        adminPageUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        adminPageUserIcon.setText("jLabel1");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email:");

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setText("john_doe@gmail.com");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Office Room:");

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setText("Level 3, Oklahoma");
        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contact Number:");

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setText("0132312312");
        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Full Name: ");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("John Doe");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Username:");

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("john_doe");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Personal Information");
        contentPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        adminPageUserIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        adminPageUserIcon1.setText("jLabel1");
        contentPanel.add(adminPageUserIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 150, 160));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Email:");
        contentPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 110, 30));

        EmailTF.setBackground(new java.awt.Color(255, 255, 255));
        EmailTF.setForeground(new java.awt.Color(0, 0, 0));
        EmailTF.setText("john_doe@gmail.com");
        EmailTF.addActionListener(this::EmailTFActionPerformed);
        contentPanel.add(EmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 220, 30));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Contact Number:");
        contentPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 170, 30));

        CNTF.setBackground(new java.awt.Color(255, 255, 255));
        CNTF.setForeground(new java.awt.Color(0, 0, 0));
        CNTF.setText("0132312312");
        CNTF.addActionListener(this::CNTFActionPerformed);
        contentPanel.add(CNTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 220, 30));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Full Name: ");
        contentPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 80, 30));

        FNTF.setBackground(new java.awt.Color(255, 255, 255));
        FNTF.setForeground(new java.awt.Color(0, 0, 0));
        FNTF.setText("John Doe");
        FNTF.addActionListener(this::FNTFActionPerformed);
        contentPanel.add(FNTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 220, 30));

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Username:");
        contentPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 80, 30));

        saveBtn.setBackground(new java.awt.Color(0, 0, 0));
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png"))); // NOI18N
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setFocusPainted(false);
        saveBtn.addActionListener(this::saveBtnActionPerformed);
        contentPanel.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 40, 40));

        UNTF.setBackground(new java.awt.Color(255, 255, 255));
        UNTF.setForeground(new java.awt.Color(0, 0, 0));
        UNTF.setText("john_doe");
        UNTF.addActionListener(this::UNTFActionPerformed);
        contentPanel.add(UNTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 220, 30));

        editBtn.setBackground(new java.awt.Color(0, 0, 0));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editBtn.setBorder(null);
        editBtn.setBorderPainted(false);
        editBtn.setContentAreaFilled(false);
        editBtn.addActionListener(this::editBtnActionPerformed);
        contentPanel.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 40, 40));

        sidebarPanel.setBackground(new java.awt.Color(0, 0, 102));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profileHeader.setBackground(new java.awt.Color(0, 0, 102));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        userIcon.setText("jLabel1");

        usernameText.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        usernameText.setForeground(new java.awt.Color(255, 255, 255));
        usernameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameText.setText("sarah_recep");

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setFocusPainted(false);
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        javax.swing.GroupLayout profileHeaderLayout = new javax.swing.GroupLayout(profileHeader);
        profileHeader.setLayout(profileHeaderLayout);
        profileHeaderLayout.setHorizontalGroup(
            profileHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        profileHeaderLayout.setVerticalGroup(
            profileHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameText)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        sidebarPanel.add(profileHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 256, 210));

        navItem01.setBackground(new java.awt.Color(0, 0, 102));
        navItem01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navItem01MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem01MouseExited(evt);
            }
        });

        navItemText01.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText01.setForeground(new java.awt.Color(255, 255, 255));
        navItemText01.setText("Manage Student Accounts");

        javax.swing.GroupLayout navItem01Layout = new javax.swing.GroupLayout(navItem01);
        navItem01.setLayout(navItem01Layout);
        navItem01Layout.setHorizontalGroup(
            navItem01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem01Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(navItemText01)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        navItem01Layout.setVerticalGroup(
            navItem01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navItem01Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(navItemText01)
                .addGap(18, 18, 18))
        );

        sidebarPanel.add(navItem01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        navItem02.setBackground(new java.awt.Color(0, 0, 102));
        navItem02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navItem02MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem02MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem02MouseExited(evt);
            }
        });

        navItemText02.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText02.setForeground(new java.awt.Color(255, 255, 255));
        navItemText02.setText("Manage appointments");

        javax.swing.GroupLayout navItem02Layout = new javax.swing.GroupLayout(navItem02);
        navItem02.setLayout(navItem02Layout);
        navItem02Layout.setHorizontalGroup(
            navItem02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem02Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(navItemText02)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        navItem02Layout.setVerticalGroup(
            navItem02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem02Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(navItemText02)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        sidebarPanel.add(navItem02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setEditMode(boolean enable) {
        // Enable/Disable Text Fields
        FNTF.setEditable(enable);
        UNTF.setEditable(enable);
        EmailTF.setEditable(enable);
        CNTF.setEditable(enable);

        // Control Button States
        editBtn.setEnabled(!enable); // Disable Edit button while editing
        saveBtn.setEnabled(enable);  // Enable Save button while editing
    }
    
    private void navItem01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem01MouseEntered
        // TODO add your handling code here:
        navItem01.setBackground(Color.orange);
        navItemText01.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_navItem01MouseEntered

    private void navItem01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem01MouseExited
        // TODO add your handling code here:
        navItem01.setBackground(new Color(0,0,102));
        navItemText01.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem01MouseExited

    private void navItem02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem02MouseEntered
        // TODO add your handling code here:
        navItem02.setBackground(Color.orange);
        navItemText02.setForeground(Color.BLACK);
    }//GEN-LAST:event_navItem02MouseEntered

    private void navItem02MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem02MouseExited
        // TODO add your handling code here:
        navItem02.setBackground(new Color(0,0,102));
        navItemText02.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem02MouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        FileHandler fh = new FileHandler();
        fh.saveDataToFiles();

        // Close current main frame and return to Login
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String newFullName = FNTF.getText().trim();
        String newUsername = UNTF.getText().trim();
        String newEmail = EmailTF.getText().trim();
        String newContact = CNTF.getText().trim();

        // Validation check
        if (newFullName.isEmpty() || newUsername.isEmpty() || newEmail.isEmpty() || newContact.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        
        currentUser.setUsername(newUsername);
        currentUser.setFullName(newFullName);
        currentUser.setReceptionistEmail(newEmail);
        currentUser.setReceptionistNumber(newContact);
        
        usernameText.setText(currentUser.getUsername());
        setEditMode(false);
        
        JOptionPane.showMessageDialog(this, "Profile updated in session!");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void UNTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UNTFActionPerformed

    private void FNTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNTFActionPerformed

    private void CNTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNTFActionPerformed

    private void EmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTFActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setEditMode(true);
        FNTF.requestFocus(); // Place cursor in the first box
    }//GEN-LAST:event_editBtnActionPerformed

    private void navItem01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem01MouseClicked
        try {
            // Try creating and displaying the frame
            ManageStudent frame = new ManageStudent(this.currentUser);
            frame.setVisible(true);

        } catch (Throwable t) {
            t.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + t.toString());
        }
    }//GEN-LAST:event_navItem01MouseClicked

    private void navItem02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem02MouseClicked
        try {
            // Try creating and displaying the frame
            ManageAppointments apptframe = new ManageAppointments(this.currentUser);
            apptframe.setVisible(true);

        } catch (Throwable t) {
            t.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + t.toString());
        }
    }//GEN-LAST:event_navItem02MouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNTF;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JTextField FNTF;
    private javax.swing.JTextField UNTF;
    private javax.swing.JLabel adminPageUserIcon;
    private javax.swing.JLabel adminPageUserIcon1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel navItem01;
    private javax.swing.JPanel navItem02;
    private javax.swing.JLabel navItemText01;
    private javax.swing.JLabel navItemText02;
    private javax.swing.JPanel profileHeader;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
